# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20161112_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'Активна'), (2, 'В процессе'), (3, 'Неактивна'), (4, 'Отменена'), (5, 'Завершена')]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='working_day',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')]),
        ),
    ]
